/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lsug.quota.model;

import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Quota service. Represents a row in the &quot;LSUGQUOTA_Quota&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lsug.quota.model.impl.QuotaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lsug.quota.model.impl.QuotaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Quota
 * @see org.lsug.quota.model.impl.QuotaImpl
 * @see org.lsug.quota.model.impl.QuotaModelImpl
 * @generated
 */
public interface QuotaModel extends AttachedModel, BaseModel<Quota> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quota model instance should use the {@link Quota} interface instead.
	 */

	/**
	 * Returns the primary key of this quota.
	 *
	 * @return the primary key of this quota
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quota.
	 *
	 * @param primaryKey the primary key of this quota
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the quota ID of this quota.
	 *
	 * @return the quota ID of this quota
	 */
	public long getQuotaId();

	/**
	 * Sets the quota ID of this quota.
	 *
	 * @param quotaId the quota ID of this quota
	 */
	public void setQuotaId(long quotaId);

	/**
	 * Returns the fully qualified class name of this quota.
	 *
	 * @return the fully qualified class name of this quota
	 */
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this quota.
	 *
	 * @return the class name ID of this quota
	 */
	public long getClassNameId();

	/**
	 * Sets the class name ID of this quota.
	 *
	 * @param classNameId the class name ID of this quota
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this quota.
	 *
	 * @return the class p k of this quota
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this quota.
	 *
	 * @param classPK the class p k of this quota
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the quota assigned of this quota.
	 *
	 * @return the quota assigned of this quota
	 */
	public long getQuotaAssigned();

	/**
	 * Sets the quota assigned of this quota.
	 *
	 * @param quotaAssigned the quota assigned of this quota
	 */
	public void setQuotaAssigned(long quotaAssigned);

	/**
	 * Returns the quota used of this quota.
	 *
	 * @return the quota used of this quota
	 */
	public long getQuotaUsed();

	/**
	 * Sets the quota used of this quota.
	 *
	 * @param quotaUsed the quota used of this quota
	 */
	public void setQuotaUsed(long quotaUsed);

	/**
	 * Returns the quota status of this quota.
	 *
	 * @return the quota status of this quota
	 */
	public int getQuotaStatus();

	/**
	 * Sets the quota status of this quota.
	 *
	 * @param quotaStatus the quota status of this quota
	 */
	public void setQuotaStatus(int quotaStatus);

	/**
	 * Returns the quota alert of this quota.
	 *
	 * @return the quota alert of this quota
	 */
	public int getQuotaAlert();

	/**
	 * Sets the quota alert of this quota.
	 *
	 * @param quotaAlert the quota alert of this quota
	 */
	public void setQuotaAlert(int quotaAlert);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Quota quota);

	public int hashCode();

	public CacheModel<Quota> toCacheModel();

	public Quota toEscapedModel();

	public String toString();

	public String toXmlString();
}