/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lsug.quota.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;

import org.lsug.quota.model.Quota;
import org.lsug.quota.model.QuotaModel;
import org.lsug.quota.model.QuotaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Quota service. Represents a row in the &quot;LSUGQUOTA_Quota&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link QuotaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuotaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotaImpl
 * @see Quota
 * @see QuotaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class QuotaModelImpl extends BaseModelImpl<Quota> implements QuotaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a quota model instance should use the {@link Quota} interface instead.
	 */
	public static final String TABLE_NAME = "LSUGQUOTA_Quota";
	public static final Object[][] TABLE_COLUMNS = {
			{ "quotaId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "quotaAssigned", Types.BIGINT },
			{ "quotaUsed", Types.BIGINT },
			{ "quotaStatus", Types.INTEGER },
			{ "quotaAlert", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("quotaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quotaAssigned", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quotaUsed", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quotaStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("quotaAlert", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table LSUGQUOTA_Quota (quotaId LONG not null primary key,companyId LONG,classNameId LONG,classPK LONG,quotaAssigned LONG,quotaUsed LONG,quotaStatus INTEGER,quotaAlert INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table LSUGQUOTA_Quota";
	public static final String ORDER_BY_JPQL = " ORDER BY quota.quotaId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LSUGQUOTA_Quota.quotaId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(org.lsug.quota.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.org.lsug.quota.model.Quota"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(org.lsug.quota.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.org.lsug.quota.model.Quota"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(org.lsug.quota.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.lsug.quota.model.Quota"),
			true);
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static final long CLASSPK_COLUMN_BITMASK = 2L;
	public static final long COMPANYID_COLUMN_BITMASK = 4L;
	public static final long QUOTAID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Quota toModel(QuotaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Quota model = new QuotaImpl();

		model.setQuotaId(soapModel.getQuotaId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setQuotaAssigned(soapModel.getQuotaAssigned());
		model.setQuotaUsed(soapModel.getQuotaUsed());
		model.setQuotaStatus(soapModel.getQuotaStatus());
		model.setQuotaAlert(soapModel.getQuotaAlert());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Quota> toModels(QuotaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Quota> models = new ArrayList<Quota>(soapModels.length);

		for (QuotaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(org.lsug.quota.service.util.ServiceProps.get(
				"lock.expiration.time.org.lsug.quota.model.Quota"));

	public QuotaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _quotaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQuotaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _quotaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Quota.class;
	}

	@Override
	public String getModelClassName() {
		return Quota.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("quotaId", getQuotaId());
		attributes.put("companyId", getCompanyId());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("quotaAssigned", getQuotaAssigned());
		attributes.put("quotaUsed", getQuotaUsed());
		attributes.put("quotaStatus", getQuotaStatus());
		attributes.put("quotaAlert", getQuotaAlert());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long quotaId = (Long)attributes.get("quotaId");

		if (quotaId != null) {
			setQuotaId(quotaId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		Long quotaAssigned = (Long)attributes.get("quotaAssigned");

		if (quotaAssigned != null) {
			setQuotaAssigned(quotaAssigned);
		}

		Long quotaUsed = (Long)attributes.get("quotaUsed");

		if (quotaUsed != null) {
			setQuotaUsed(quotaUsed);
		}

		Integer quotaStatus = (Integer)attributes.get("quotaStatus");

		if (quotaStatus != null) {
			setQuotaStatus(quotaStatus);
		}

		Integer quotaAlert = (Integer)attributes.get("quotaAlert");

		if (quotaAlert != null) {
			setQuotaAlert(quotaAlert);
		}
	}

	@JSON
	@Override
	public long getQuotaId() {
		return _quotaId;
	}

	@Override
	public void setQuotaId(long quotaId) {
		_quotaId = quotaId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return StringPool.BLANK;
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@JSON
	@Override
	public long getQuotaAssigned() {
		return _quotaAssigned;
	}

	@Override
	public void setQuotaAssigned(long quotaAssigned) {
		_quotaAssigned = quotaAssigned;
	}

	@JSON
	@Override
	public long getQuotaUsed() {
		return _quotaUsed;
	}

	@Override
	public void setQuotaUsed(long quotaUsed) {
		_quotaUsed = quotaUsed;
	}

	@JSON
	@Override
	public int getQuotaStatus() {
		return _quotaStatus;
	}

	@Override
	public void setQuotaStatus(int quotaStatus) {
		_quotaStatus = quotaStatus;
	}

	@JSON
	@Override
	public int getQuotaAlert() {
		return _quotaAlert;
	}

	@Override
	public void setQuotaAlert(int quotaAlert) {
		_quotaAlert = quotaAlert;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Quota.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Quota toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Quota)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QuotaImpl quotaImpl = new QuotaImpl();

		quotaImpl.setQuotaId(getQuotaId());
		quotaImpl.setCompanyId(getCompanyId());
		quotaImpl.setClassNameId(getClassNameId());
		quotaImpl.setClassPK(getClassPK());
		quotaImpl.setQuotaAssigned(getQuotaAssigned());
		quotaImpl.setQuotaUsed(getQuotaUsed());
		quotaImpl.setQuotaStatus(getQuotaStatus());
		quotaImpl.setQuotaAlert(getQuotaAlert());

		quotaImpl.resetOriginalValues();

		return quotaImpl;
	}

	@Override
	public int compareTo(Quota quota) {
		long primaryKey = quota.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Quota)) {
			return false;
		}

		Quota quota = (Quota)obj;

		long primaryKey = quota.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		QuotaModelImpl quotaModelImpl = this;

		quotaModelImpl._originalCompanyId = quotaModelImpl._companyId;

		quotaModelImpl._setOriginalCompanyId = false;

		quotaModelImpl._originalClassNameId = quotaModelImpl._classNameId;

		quotaModelImpl._setOriginalClassNameId = false;

		quotaModelImpl._originalClassPK = quotaModelImpl._classPK;

		quotaModelImpl._setOriginalClassPK = false;

		quotaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Quota> toCacheModel() {
		QuotaCacheModel quotaCacheModel = new QuotaCacheModel();

		quotaCacheModel.quotaId = getQuotaId();

		quotaCacheModel.companyId = getCompanyId();

		quotaCacheModel.classNameId = getClassNameId();

		quotaCacheModel.classPK = getClassPK();

		quotaCacheModel.quotaAssigned = getQuotaAssigned();

		quotaCacheModel.quotaUsed = getQuotaUsed();

		quotaCacheModel.quotaStatus = getQuotaStatus();

		quotaCacheModel.quotaAlert = getQuotaAlert();

		return quotaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{quotaId=");
		sb.append(getQuotaId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", quotaAssigned=");
		sb.append(getQuotaAssigned());
		sb.append(", quotaUsed=");
		sb.append(getQuotaUsed());
		sb.append(", quotaStatus=");
		sb.append(getQuotaStatus());
		sb.append(", quotaAlert=");
		sb.append(getQuotaAlert());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.lsug.quota.model.Quota");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>quotaId</column-name><column-value><![CDATA[");
		sb.append(getQuotaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quotaAssigned</column-name><column-value><![CDATA[");
		sb.append(getQuotaAssigned());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quotaUsed</column-name><column-value><![CDATA[");
		sb.append(getQuotaUsed());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quotaStatus</column-name><column-value><![CDATA[");
		sb.append(getQuotaStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quotaAlert</column-name><column-value><![CDATA[");
		sb.append(getQuotaAlert());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Quota.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Quota.class
		};
	private long _quotaId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private long _quotaAssigned;
	private long _quotaUsed;
	private int _quotaStatus;
	private int _quotaAlert;
	private long _columnBitmask;
	private Quota _escapedModel;
}