/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lsug.quota.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.lsug.quota.model.Quota;
import org.lsug.quota.service.QuotaLocalServiceUtil;

/**
 * The extended model base implementation for the Quota service. Represents a row in the &quot;LSUGQUOTA_Quota&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuotaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuotaImpl
 * @see org.lsug.quota.model.Quota
 * @generated
 */
public abstract class QuotaBaseImpl extends QuotaModelImpl implements Quota {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a quota model instance should use the {@link Quota} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			QuotaLocalServiceUtil.addQuota(this);
		}
		else {
			QuotaLocalServiceUtil.updateQuota(this);
		}
	}
}